apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  mode: deployment

  image: otel/opentelemetry-collector-contrib:0.114.0

  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"

      otlp/tempo:
        endpoint: tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

      loki:
        endpoint: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus]

        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/tempo]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]
