# github actions pipeline

name: KBOT-CICD

# Allow github actions to commit code
permissions:
  contents: write

# Event that triggers this job 
on:
  #push:
  #  branches:
  #    - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    #Run on github hosted ubuntu 
    runs-on: ubuntu-latest
    #Run on self-hosted runner
    #runs-on: self-hosted

    steps:
      # Fetch the repo code from runner
      - name: Checkout.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # we need all history for bracnhes and tags because we use it for versioning in Makefile
      - name: Run test
        run: make test
      
      - name: Docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: "docker.io"
        run: make print-env image push
    
  cd:
    name: CD
    needs: ci #starts only if ci job finished well
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Pass VERSION to HITHUBENV, so shared with other steps
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    # Set current image TAG in helm chart.
    - name: Update Helm chart
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
    
    - name: Commit Helm chart changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "chore: update version to $VERSION"
        git push
    
    - name: Clone Flux repo
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/dmzopi/fluxcd-eks.git fluxcd-eks
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        
    - name: Load secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          TELE_TOKEN_S,kbot/tele_token

    - name: Generate Kubernetes Secret
      run: |
        mkdir -p fluxcd-eks/clusters/k8s-flux-eks/kbot
        TOKEN_B64=$(echo -n "$TELE_TOKEN_S" | base64 -w 0)
        cat > fluxcd-eks/clusters/k8s-flux-eks/kbot/kbot-secret.yaml << 'EOF'
        apiVersion: v1
        kind: Secret
        metadata:
          name: kbot
          namespace: demo
        data:
          token: $TOKEN_B64
        EOF

    # Or use TELE_TOKEN stored in github secrets 
    #- name: Generate Kubernetes Secret
    #  run: |
    #    mkdir -p fluxcd-eks/clusters/k8s-flux-eks/kbot
    #    cat <<EOF > fluxcd-eks/clusters/k8s-flux-eks/kbot/kbot-secret.yaml
    #    apiVersion: v1
    #    kind: Secret
    #    metadata:
    #      name: kbot
    #      namespace: demo
    #    type: Opaque
    #    stringData:
    #      token: "${{ secrets.TELE_TOKEN }}"
    #    EOF

    - name: Install SOPS.
      run: |

        curl -LO https://github.com/getsops/sops/releases/download/v3.13.1/sops-v3.13.1.linux.amd64

        chmod +x sops-v3.13.1.linux.amd64
        sudo mv sops-v3.13.1.linux.amd64 /usr/local/bin/sops

        sops --version

    - name: Encrypt secret with SOPS
      run: |
        sops -e --kms "${{ secrets.KMS_KEY }}" --encrypted-regex '^(token)$' fluxcd-eks/clusters/k8s-flux-eks/kbot/kbot-secret.yaml > fluxcd-eks/clusters/k8s-flux-eks/kbot/kbot-secret-cyph.yaml

    - name: Commit to Flux repo
      run: |
        cd fluxcd-eks

        git config user.name github-actions
        git config user.email github-actions@github.com

        git add clusters/k8s-flux-eks/kbot/kbot-secret-cyph.yaml

        git commit -m "chore: add encrypted kbot secret" || echo "no changes"
        git push

      
