name: KBOT-CICD

# Event that triggers job 
on: push

jobs:
  ci:
    name: CI
    #Runner with run on githib vm, ubuntu 
    runs-on: ubuntu-latest
    #Run on self-hosted runner
    #runs-on: self-hosted

    steps:
      # Fetch the repo code to runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # we need all history for bracnhes and tags, beacuse we use it for versioning in Makefile
      - name: Run test
        run: make test
      
      - name: Docker hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make image push
    
  cd:
    name: CD
    needs: ci #starts only is ci job finished well
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Pass VERSION to HITHUBENV, so shared with other steps
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    # Set current image TAG in helm chart 
    - name: Update Helm chart
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
    
    - name: Commit Helm chart changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "chore: update version to $VERSION"
        git push

