name: KBOT-CICD

# Event that triggers job 
on: 
  push:
    branches: [ develop ]

jobs:
  ci:
    name: CI
    #Runner with run on githib vm, ubuntu 
    runs-on: ubuntu-latest
    #Run on self-hosted runner
    #runs-on: self-hosted
    permissions:
      #contents: read
      packages: write  # Crucial for ghcr.io push

    steps:
      # Fetch the repo code to runner
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # we need all history for bracnhes and tags, beacuse we use it for versioning in Makefile
      - name: Run test
        run: make test
      
      - name: Log in to the Container registry ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ghcr.io
          REPO: dmzopi
        run: |
          make image push
          IMAGE_REPO="${REGISTRY}/${REPO}"
          echo "image_repo=$IMAGE_REPO" >> $GITHUB_OUTPUT

  cd:
    name: CD
    needs: ci #starts only is ci job finished well 
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Pass VERSION to HITHUBENV, so shared with other steps
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    # Set current image TAG in helm chart 
    - name: Update Helm RE
      env:
        IMAGE_REPO: ${{ needs.ci.outputs.image_repo }}
      uses: mikefarah/yq@master
      with:
        cmd: >
          echo "IMAGE_REPO=${IMAGE_REPO}" &&
          yq -i '.image.repository=strenv(IMAGE_REPO)' helm/values.yaml &&
          yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

    - name: Commit Helm chart changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "CD: update version to $VERSION, image $IMAGE_REPO"
        git push